# -*- coding: utf-8 -*-
"""Password_Cracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fk9UaK75c8dOhB0jUxiq4EOCnvPR8R72
"""



#password_cracker
from random import *
user_pass= input("Enter Password")
password= ['a','b','c','d', 'e', 'f', 'g', 'h', 'i', 'j','k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '!', '@', '#', '$', '%', '&', '*', '?']
guess=''

while(guess!=user_pass):
  guess=''
  for letter in range(len(user_pass)):
    guess_letter= password[randint(0,69)]
    guess=str(guess_letter)+str(guess)
    print(guess)
    print()